# Generated by Django 4.0.3 on 2022-11-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='mail',
            new_name='email',
        ),
    ]
